### ISSUE TITLE
При генерации файлов для Mikrotik добавляется лишний слэш

### ISSUE THREAD

**Issue by Just-AndyE** [fedor2018/wireguard-mikrotik#1]
При генерации файлов для Mikrotik при генерации команды добавления правила файервола в конце команды добавляется лишний слэш который приводит к невозможности запустить скрипт из консоли роутера.
`/ip/firewall/filter add \
    action=accept comment=wg0srv chain=input dst-port=45250 protocol=udp \`

**Comment by fedor2018** [comment]
удалил
